In [1]:
!pip install nba_api

Collecting nba_api
  Downloading nba_api-1.1.8-py3-none-any.whl (217 kB)
     |████████████████████████████████| 217 kB 492 kB/s eta 0:00:01
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.7/site-packages (from nba_api) (2.22.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/anaconda3/lib/python3.7/site-packages (from requests->nba_api) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/anaconda3/lib/python3.7/site-packages (from requests->nba_api) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in /opt/anaconda3/lib/python3.7/site-packages (from requests->nba_api) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.7/site-packages (from requests->nba_api) (2019.11.28)
Installing collected packages: nba-api
Successfully installed nba-api-1.1.8

In [13]:
from nba_api.stats.static import teams
from nba_api.stats.endpoints import leaguegamefinder

import pandas as pd
import sqlite3

In [14]:
team_data=teams.get_teams()

In [15]:
connection = sqlite3.connect('data/nba.db')

In [16]:
for t in team_data:
    gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=t['id'])
    games = gamefinder.get_data_frames()[0]
    games['opponent']=games.MATCHUP.apply(lambda x: x[-3:])#x.split(' @ '))
    games.to_sql(t['abbreviation'], connection, if_exists='replace')

ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)

In [17]:
pd.read_sql('''
SELECT 
*
FROM sqlite_master 
where type='table'
''', connection)

,type,name,tbl_name,rootpage,sql
0,table,BOS-target,BOS-target,3783,"CREATE TABLE ""BOS-target"" (\n""index"" INTEGER,\..."
1,table,CLE-target,CLE-target,3917,"CREATE TABLE ""CLE-target"" (\n""index"" INTEGER,\..."
2,table,NOP-target,NOP-target,4051,"CREATE TABLE ""NOP-target"" (\n""index"" INTEGER,\..."
3,table,CHI-target,CHI-target,4120,"CREATE TABLE ""CHI-target"" (\n""index"" INTEGER,\..."
4,table,DAL-target,DAL-target,4251,"CREATE TABLE ""DAL-target"" (\n""index"" INTEGER,\..."
5,table,DEN-target,DEN-target,4382,"CREATE TABLE ""DEN-target"" (\n""index"" INTEGER,\..."
6,table,GSW-target,GSW-target,4509,"CREATE TABLE ""GSW-target"" (\n""index"" INTEGER,\..."
7,table,HOU-target,HOU-target,4642,"CREATE TABLE ""HOU-target"" (\n""index"" INTEGER,\..."
8,table,LAC-target,LAC-target,4773,"CREATE TABLE ""LAC-target"" (\n""index"" INTEGER,\..."
9,table,LAL-target,LAL-target,4902,"CREATE TABLE ""LAL-target"" (\n""index"" INTEGER,\..."
10,table,MIA-target,MIA-target,5041,"CREATE TABLE ""MIA-target"" (\n""index"" INTEGER,\..."
11,table,MIL-target,MIL-target,5153,"CREATE TABLE ""MIL-target"" (\n""index"" INTEGER,\..."
12,table,MIN-target,MIN-target,5281,"CREATE TABLE ""MIN-target"" (\n""index"" INTEGER,\..."
13,table,BKN-target,BKN-target,5391,"CREATE TABLE ""BKN-target"" (\n""index"" INTEGER,\..."
14,table,NYK-target,NYK-target,5518,"CREATE TABLE ""NYK-target"" (\n""index"" INTEGER,\..."
15,table,ORL-target,ORL-target,5647,"CREATE TABLE ""ORL-target"" (\n""index"" INTEGER,\..."
16,table,IND-target,IND-target,5752,"CREATE TABLE ""IND-target"" (\n""index"" INTEGER,\..."
17,table,PHI-target,PHI-target,5881,"CREATE TABLE ""PHI-target"" (\n""index"" INTEGER,\..."
18,table,PHX-target,PHX-target,6011,"CREATE TABLE ""PHX-target"" (\n""index"" INTEGER,\..."
19,table,POR-target,POR-target,6138,"CREATE TABLE ""POR-target"" (\n""index"" INTEGER,\..."
20,table,SAC-target,SAC-target,6273,"CREATE TABLE ""SAC-target"" (\n""index"" INTEGER,\..."
21,table,SAS-target,SAS-target,6399,"CREATE TABLE ""SAS-target"" (\n""index"" INTEGER,\..."
22,table,OKC-target,OKC-target,6535,"CREATE TABLE ""OKC-target"" (\n""index"" INTEGER,\..."
23,table,TOR-target,TOR-target,6669,"CREATE TABLE ""TOR-target"" (\n""index"" INTEGER,\..."
24,table,UTA-target,UTA-target,6760,"CREATE TABLE ""UTA-target"" (\n""index"" INTEGER,\..."
25,table,MEM-target,MEM-target,6888,"CREATE TABLE ""MEM-target"" (\n""index"" INTEGER,\..."
26,table,WAS-target,WAS-target,6977,"CREATE TABLE ""WAS-target"" (\n""index"" INTEGER,\..."
27,table,DET-target,DET-target,7103,"CREATE TABLE ""DET-target"" (\n""index"" INTEGER,\..."
28,table,CHA-target,CHA-target,7236,"CREATE TABLE ""CHA-target"" (\n""index"" INTEGER,\..."
29,table,ATL-target,ATL-target,3658,"CREATE TABLE ""ATL-target"" (\n""index"" INTEGER,\..."
30,table,PHI,PHI,2296,"CREATE TABLE ""PHI"" (\n""index"" INTEGER,\n ""SEA..."
31,table,PHX,PHX,2425,"CREATE TABLE ""PHX"" (\n""index"" INTEGER,\n ""SEA..."
32,table,POR,POR,2551,"CREATE TABLE ""POR"" (\n""index"" INTEGER,\n ""SEA..."
33,table,SAC,SAC,2686,"CREATE TABLE ""SAC"" (\n""index"" INTEGER,\n ""SEA..."
34,table,SAS,SAS,2811,"CREATE TABLE ""SAS"" (\n""index"" INTEGER,\n ""SEA..."
35,table,OKC,OKC,2947,"CREATE TABLE ""OKC"" (\n""index"" INTEGER,\n ""SEA..."
36,table,TOR,TOR,2,"CREATE TABLE ""TOR"" (\n""index"" INTEGER,\n ""SEA..."
37,table,UTA,UTA,3083,"CREATE TABLE ""UTA"" (\n""index"" INTEGER,\n ""SEA..."
38,table,MEM,MEM,3208,"CREATE TABLE ""MEM"" (\n""index"" INTEGER,\n ""SEA..."
39,table,WAS,WAS,3296,"CREATE TABLE ""WAS"" (\n""index"" INTEGER,\n ""SEA..."
40,table,DET,DET,3422,"CREATE TABLE ""DET"" (\n""index"" INTEGER,\n ""SEA..."
41,table,CHA,CHA,3554,"CREATE TABLE ""CHA"" (\n""index"" INTEGER,\n ""SEA..."
42,table,ATL,ATL,89,"CREATE TABLE ""ATL"" (\n""index"" INTEGER,\n ""SEA..."
43,table,BOS,BOS,214,"CREATE TABLE ""BOS"" (\n""index"" INTEGER,\n ""SEA..."
44,table,CLE,CLE,346,"CREATE TABLE ""CLE"" (\n""index"" INTEGER,\n ""SEA..."
45,table,NOP,NOP,477,"CREATE TABLE ""NOP"" (\n""index"" INTEGER,\n ""SEA..."
46,table,CHI,CHI,545,"CREATE TABLE ""CHI"" (\n""index"" INTEGER,\n ""SEA..."
47,table,DAL,DAL,674,"CREATE TABLE ""DAL"" (\n""index"" INTEGER,\n ""SEA..."
48,table,DEN,DEN,806,"CREATE TABLE ""DEN"" (\n""index"" INTEGER,\n ""SEA..."
49,table,GSW,GSW,931,"CREATE TABLE ""GSW"" (\n""index"" INTEGER,\n ""SEA..."
50,table,HOU,HOU,1064,"CREATE TABLE ""HOU"" (\n""index"" INTEGER,\n ""SEA..."
51,table,LAC,LAC,1195,"CREATE TABLE ""LAC"" (\n""index"" INTEGER,\n ""SEA..."
52,table,LAL,LAL,1322,"CREATE TABLE ""LAL"" (\n""index"" INTEGER,\n ""SEA..."
53,table,MIA,MIA,1460,"CREATE TABLE ""MIA"" (\n""index"" INTEGER,\n ""SEA..."
54,table,MIL,MIL,1573,"CREATE TABLE ""MIL"" (\n""index"" INTEGER,\n ""SEA..."
55,table,MIN,MIN,1700,"CREATE TABLE ""MIN"" (\n""index"" INTEGER,\n ""SEA..."
56,table,BKN,BKN,1810,"CREATE TABLE ""BKN"" (\n""index"" INTEGER,\n ""SEA..."
57,table,NYK,NYK,1935,"CREATE TABLE ""NYK"" (\n""index"" INTEGER,\n ""SEA..."
58,table,ORL,ORL,2063,"CREATE TABLE ""ORL"" (\n""index"" INTEGER,\n ""SEA..."
59,table,IND,IND,2168,"CREATE TABLE ""IND"" (\n""index"" INTEGER,\n ""SEA..."

In [18]:
pd.read_sql("select * from sas", connection).columns

Index(['index', 'SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME',
       'GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'PTS', 'FGM', 'FGA',
       'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB',
       'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PLUS_MINUS',
       'opponent'],
      dtype='object')

In [11]:
connection.close()